### ISSUE TITLE
[Lv.1 To Do List] 질문 및 코드 리뷰

### ISSUE THREAD

**Issue by hansololiviakim** [Olivia-Study-Storage/hh99-react-beginner#2]
# :question: Review
### **이번 과제에서 중점을 둔 사항**
1. HTML 태그는 시맨틱하게 작성하기 위해 노력했습니다.　ex. section, label, strong...
2. 변수명은 알아보기 쉽게 작성할 수 있도록 고려하였습니다.
3. 컴포넌트 분리는 화면 레이아웃을 기준으로 먼저 나누고, 중복되는 세부 기능이 있다면 추가로 컴포넌트화 하는 순서로 진행했습니다.

<br/>

### **질의사항**
1. 변수명을 HTML 부분은 스네이크 케이스, JavaScript 부분은 카멜케이스로 표기하였는데 하나로 통일하는게 더 나은지, 어느 표기법을 더 권장하시는지 궁금합니다.
2. List 컴포넌트의 경우 현재의 Woring 부분과 Done 부분을 더 세부적으로 컴포넌트화하거나 아니면 하나로 합칠 수 있는 부분이 있는지 알고 싶습니다.
3. 컴포넌트를 나눌 때 CSS 파일도 컴포넌트에 맞춰 나눠야 하는지 궁금합니다. 만약 나눈다면, 폴더 어느 곳에 위치시키면 될까요?
4. 이번 과제를 하며 컴포넌트 분리하는게 손에 익지 않아 App.jsx에 모든 코드를 작성해 구현하고 이후 컴포넌트를 분리해보는 식으로 구현하였습니다. 손에 익게되면 컴포넌트를 바로 나누면서 개발이 가능한지, 아니면 지금은 이 방법도 괜찮은지 궁금합니다.
5. 지금은 삭제한 내용에 대해서는 filter를 거는데 데이터 양이 아주 많아졌을 경우에도 불변성을 지키기 위해 원본 배열을 직접적으로 삭제를 하지 않는 형식으로 진행되는지, 실무에서도 덮어 씌우는 방식으로 값을 변경하는지 궁금합니다. 더 좋은 방법이 있다면 알고 싶습니다.

<br/>

감사합니다.

**Comment by endol007** [comment]
1. html부분을 스네이크케이스로 하셨다는건 id나 css 클래스명을 말씀하신 것 같은데 보통은 케밥케이스를 많이 사용합니다. js는 사용하신대로 카멜케이스로 사용하면 될 것 같아요.
2. 하나로 합치는것 보단 working과 done을 구분해서 컴포넌트를 만드는 걸 추천드려요. 데이터의 쓰임새가 다르기 때문에 굳이 합칠 필요가 없습니다.
3. css는 파일은 보통 별도로 관리를 하는 편입니다.
4. 처음에 구현하실 때는 지금 방법을 사용하면서 공부하는게 편할거에요. 어차피 숙달되면 바로 컴포넌트들을 나누고 개발을 하게됩니다
5. react에서 데이터를 다룰 때는 원본배열을 직접 삭제하는 일이 거의 없습니다. 지금 처럼 filter로 사용을 하면되고 실무에서는 데이터의 양이 아주 많아질 경우에는 처음부터 백엔드에서 쪼개서 주는걸 받게 될거에요
